In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5788, 2255, 2021, 4917],
 [5788, 2255, 2021, 3352],
 [5788, 2234, 2021, 3141],
 [1903, 5721, 7287, 5192, 370],
 [1903, 5721, 7287, 5192, 5505],
 [5473, 5788, 654, 2021, 4164],
 [8925, 2056, 7080, 5192]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5788 2255 2021 4917]
 [   0    0    0    0 5788 2255 2021 3352]
 [   0    0    0    0 5788 2234 2021 3141]
 [   0    0    0 1903 5721 7287 5192  370]
 [   0    0    0 1903 5721 7287 5192 5505]
 [   0    0    0 5473 5788  654 2021 4164]
 [   0    0    0    0 8925 2056 7080 5192]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step


array([[[ 0.0061108 , -0.00049661, -0.03196595, -0.0015582 ,
         -0.01255591,  0.04261524,  0.00665864,  0.0285862 ,
          0.03477154,  0.00464697],
        [ 0.0061108 , -0.00049661, -0.03196595, -0.0015582 ,
         -0.01255591,  0.04261524,  0.00665864,  0.0285862 ,
          0.03477154,  0.00464697],
        [ 0.0061108 , -0.00049661, -0.03196595, -0.0015582 ,
         -0.01255591,  0.04261524,  0.00665864,  0.0285862 ,
          0.03477154,  0.00464697],
        [ 0.0061108 , -0.00049661, -0.03196595, -0.0015582 ,
         -0.01255591,  0.04261524,  0.00665864,  0.0285862 ,
          0.03477154,  0.00464697],
        [-0.03727822, -0.03950859,  0.00817249, -0.03636573,
          0.03701289,  0.02078852,  0.00112665,  0.00010897,
          0.029417  , -0.03566928],
        [-0.02479007,  0.0099312 , -0.04202376, -0.01193346,
         -0.02844055,  0.04540202, -0.04803865, -0.00683721,
         -0.03012273,  0.02105946],
        [ 0.02126728,  0.02618767,  0.02457524, -0.0

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531